#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MicroArchitecture {
    Airmont,
    AlderLake,
    Atom,
    ArrowLake, // Gen 15 (0xC6, -H = 0xC5)
    Broadwell,
    CannonLake,
    CometLake,
    Core,
    Goldmont,
    GoldmontPlus,
    Haswell,
    IceLake,
    IvyBridge,
    JasperLake,
    KabyLake,
    LunarLake,
    Nehalem,
    NetBurst,
    MeteorLake,
    RocketLake,
    SandyBridge,
    Silvermont,
    Skylake,
    TigerLake,
    Tremont,
    RaptorLake,
    SapphireRapids,
    ElkhartLake,
    Unknown,
}
